events {}
http {
  upstream service_a { server service-a:5001; }
  upstream service_b { server service-b:5002; }

  server {
    listen 80;

    location /a/ {
      proxy_pass http://service_a/;
      proxy_set_header Host $host;
      proxy_set_header X-Real-IP $remote_addr;
    }

    location /b/ {
      proxy_pass http://service_b/;
      proxy_set_header Host $host;
      proxy_set_header X-Real-IP $remote_addr;
    }

    location = /healthz {
      add_header Content-Type text/plain;
      return 200 "ok\n";
    }
  }
}

